### ISSUE TITLE
duct.core/prep should load config namespaces before modules

### ISSUE THREAD

**Issue by jahson** [duct-framework/core#7]
I've set up an [repository](https://github.com/jahson/duct-core-issue) for reproduction.

Reproduction steps:

1. `git clone git@github.com:jahson/duct-core-issue.git`
2. `cd duct-core-issue`
3. `lein repl`
4. `(dev)`
5. `(go)`

You will see

```
dev=> (go)
:duct.server.http.jetty/starting-server {:port 3000}
авг 28, 2017 2:27:52 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.6.Final
авг 28, 2017 2:27:52 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.6.Final
:initiated
```

Note the `:duct.server.http.jetty/starting-server {:port 3000}` log message.

Run `(reset)` after that:

```
dev=> (reset)
:reloading (example.main example.server.http.immutant dev user)
:duct.server.http.jetty/stopping-server
:example.server.http.immutant/starting-server {:port 3000}
:resumed
```

Note the `:example.server.http.immutant/starting-server {:port 3000}` log message this time.

Expected behaviour is `:example.server.http.immutant/starting-server {:port 3000}` each time.

It works as expected if I use `duct_hierarchy.edn` that contains

```
{:example.server.http/immutant [:duct.server/http]}
```

AFAIK it happens because of modules are applied before namespaces loaded.
```
  ([config keys {:keys [readers] :or {readers {}}}]
   (-> config
       (apply-includes (memoize #(read-config % readers)))
       (doto (ig/load-namespaces [:duct/module]))
       (apply-modules)
       (doto (as-> cfg (if keys
                         (ig/load-namespaces cfg keys)
                         (ig/load-namespaces cfg)))))))
```

Moving call to `(apply-modules)` lower in chain helps with the right server key being provided with port etc., but everything will fail after `(init)`:

```
IllegalArgumentException No method in multimethod 'init-key' for dispatch value: :duct.middleware.web/stacktrace  clojure.lang.MultiFn.getFn (MultiFn.java:156)
```

It looks like `duct.middleware.web` namespace wasn't loaded (because I moved `(apply-modules)` lower in chain in my local copy of `duct.core`).

**Comment by jahson** [comment]
It will work if we'll call to `ig/load-namespaces` again, after `(apply-modules)`, though this looks awful.

```
([config keys {:keys [readers] :or {readers {}}}]
   (-> config
       (apply-includes (memoize #(read-config % readers)))
       (doto (ig/load-namespaces [:duct/module]))
       (doto (as-> cfg (if keys
                         (ig/load-namespaces cfg keys)
                         (ig/load-namespaces cfg))))))
       (apply-modules)
       (doto (as-> cfg (if keys
                         (ig/load-namespaces cfg keys)
                         (ig/load-namespaces cfg)))))))
```

**Comment by weavejester** [comment]
> It works as expected if I use duct_hierarchy.edn that contains
>
>     {:example.server.http/immutant [:duct.server/http]}

This is what you should be doing :)

I had forgotten that this would apply if you write a custom web server, because of the way the web module looks for an existing HTTP server before adding its own. I need to make this behaviour clearer, and devote a part of the [duct/core](https://github.com/duct-framework/core) README to an explanation.

The `duct_hierarchy.edn` files were added in to get around the problem of having to load up unnecessary namespaces, since as I'm sure you're aware, loading namespaces is expensive in Clojure. The more we load, the greater the startup time.

If you have a SQL-backed web application, you don't want to load in the web server if all you want to do is migrate the database. If you have a ClojureScript application, you don't want to load in the ClojureScript compiler if the ClojureScript code has already been compiled.

Yet at the same time, we do want the semantic information that the keys ancestors give us. We want to know what keys are relevant for our current operation. If we're migrating the database, we want to know which key is derived from `:duct.database/sql`, for instance.

This is where `duct_hierarchy.edn` comes in, and occupies a similar space to `data_readers.clj`. It's edn only, so it's very fast to read, and provides the keyword hierarchy that Duct needs to understand the system the configuration produces.

**Comment by jahson** [comment]
> This is what you should be doing :)

Yeah, will definitely do that. This issue is more for clarification of details. By your commits I understood that hierarchy moved to `duct_hierarchy.edn` files, but wasn't sure if I should move all derived keys to these files. Also I was confused to see `jetty` starting instead of `immutant`, but your code and explanation clarified things a lot. And the final conclusion is that I can still use `derive` in clojure file or choose`duct_hierarchy.edn` if I want to load only necessary namespaces. The root of this issue was in web module.

> I need to make this behaviour clearer, and devote a part of the duct/core README to an explanation.

An explanation of these things in README would, probably, be very helpful because there can be other cases like this.

Thank you for your work and explanations.
